"use client";
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogTrigger} from '@/components/ui/dialog';
import type {Reading} from '@/lib/reading';
type Comment={id:string;parent_id:string|null;name:string;body:string;created_at:string};
export default function Discussion({reading}:{reading:Reading}){const [open,setOpen]=useState(false),[comments,setComments]=useState<Comment[]>([]),[status,setStatus]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[parent,setParent]=useState<Comment|null>(null);
async function load(){setLoading(true);try{const r=await fetch('/api/discussions?reading='+reading.id);const d=await r.json() as {error?:string;comments:Comment[]};if(!r.ok)throw Error(d.error);setComments(d.comments)}catch(e){setStatus(e instanceof Error?e.message:'Unable to load discussion.')}finally{setLoading(false)}}
useEffect(()=>{if(open){setStatus('');void load()}},[open]);
function comment(c:Comment){return <article className="discussion-comment" key={c.id}><p className="fine">{c.name} · {new Date(c.created_at).toLocaleDateString()}</p><p className="discussion-body">{c.body}</p>{!c.parent_id&&<button className="reply-button" onClick={()=>setParent(c)}>Reply to {c.name}</button>}</article>}
return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button className="button">Questions & discussion</button></DialogTrigger><DialogContent className="project-dialog"><DialogTitle>{reading.title}</DialogTitle><DialogDescription>Public conversation · Names are provided by visitors and are not verified.</DialogDescription><div aria-live="polite">{loading?<p>Loading discussion…</p>:<>{!comments.length&&<p>No comments yet. Start the conversation.</p>}{comments.filter(c=>!c.parent_id).map(c=><div key={c.id}>{comment(c)}<div className="discussion-replies">{comments.filter(r=>r.parent_id===c.id).map(comment)}</div></div>)}</>}</div><button className="reply-button" onClick={()=>{setStatus('');void load()}}>Refresh discussion</button><form className="message-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setStatus('');const form=e.currentTarget;const f=new FormData(form);try{const r=await fetch('/api/discussions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reading:reading.id,parent:parent?.id||null,name:f.get('name'),body:f.get('body'),website:f.get('website')})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);form.reset();setParent(null);setStatus('Your comment is now public.');await load()}catch(err){setStatus(err instanceof Error?err.message:'Please try again.')}finally{setBusy(false)}}}>{parent&&<p>Replying to {parent.name} <button type="button" className="reply-button" onClick={()=>setParent(null)}>Cancel reply</button></p>}<label>Display name<input name="name" required maxLength={60} autoComplete="nickname"/></label><label>{parent?'Your reply':'Your question or discussion'}<textarea name="body" required minLength={5} maxLength={1500} rows={4}/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="fine">Your name and message will be visible to everyone. Keep it thoughtful; leave contact details out.</p><button className="button primary" disabled={busy}>{busy?'Posting…':parent?'Post public reply':'Post public comment'}</button><p role="status">{status}</p></form></DialogContent></Dialog>}
