"use client";
import {useState} from "react";
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {projects,skills,faqs} from "@/lib/portfolio";
function Heading({children}:{children:React.ReactNode}){return <div className="heading-band"><h2>{children}</h2></div>}
function MessageForm({kind,question,onSent}:{kind:"note"|"question";question?:string;onSent?:(sent:boolean)=>void}){
 const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 return <form className="message-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setStatus("");const form=e.currentTarget;const data=new FormData(form);try{const r=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,name:data.get("name"),email:data.get("email"),body:question||data.get("body"),website:data.get("website")})});const result=await r.json() as {error?:string;emailSent:boolean};if(!r.ok)throw Error(result.error||"Please try again.");setStatus(kind==="note"?"Your note was saved privately for Madhumita.":result.emailSent?"Your question was saved and emailed to Madhumita.":"Your question was saved in Madhumita’s private inbox. Email delivery is not available yet.");form.reset();onSent?.(result.emailSent)}catch(err){setStatus(err instanceof Error?err.message:"Please try again.")}finally{setBusy(false)}}}>
 <div className="form-pair"><label>Your name <span>(optional)</span><input name="name" maxLength={80} autoComplete="name"/></label><label>Email <span>(optional, for a reply)</span><input name="email" type="email" maxLength={254} autoComplete="email"/></label></div>
 {!question&&<label>Your note<textarea name="body" required minLength={5} maxLength={2000} rows={4} placeholder="A hello, feedback, or an opportunity…"/></label>}
 <label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>
 <p className="fine">Only Madhumita can read submissions. Don’t include sensitive personal information.</p><button className="button primary" disabled={busy}>{busy?"Saving…":kind==="note"?"Leave a private note":"Send question to Madhumita"}</button><p role="status">{status}</p></form>
}
function Pet(){
 const [open,setOpen]=useState(false);const [question,setQuestion]=useState("");const [asked,setAsked]=useState("");const [answer,setAnswer]=useState("");const [unknown,setUnknown]=useState(false);const [wiggle,setWiggle]=useState(false);
 async function ask(q:string){const clean=q.trim();if(!clean)return;setAsked(clean);setUnknown(false);const matched=faqs.find(f=>f.q.toLowerCase()===clean.toLowerCase())||(!/salary|visa|sponsor|citizen|available|start date|graduate|graduat|age|marri|relig|politic|address|gpa|years|percent|accuracy|favorite/i.test(clean)?faqs.find(f=>f.patterns.some(p=>p.test(clean.toLowerCase()))):undefined);if(matched){setAnswer(matched.answer)}else{setAnswer("I don’t have a verified answer to that. I’m forwarding your question to Madhumita…");setUnknown(true);try{const r=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"question",body:clean})});const result=await r.json() as {error?:string;emailSent:boolean};if(!r.ok)throw Error(result.error||"Please try again.");setAnswer(result.emailSent?"I don’t know that one! Your question was saved privately and emailed to Madhumita. Leave a private note with your email if you’d like a reply.":"I don’t know that one! Your question was saved in Madhumita’s private inbox. Email delivery is currently unavailable.")}catch(err){setAnswer("I don’t know that one, and couldn’t forward it. "+(err instanceof Error?err.message:"Please try again."))}}}
 return <><button className={"pet-launch "+(wiggle?"pet-wiggle":"")} onClick={()=>setOpen(true)} onMouseEnter={()=>setWiggle(true)} onAnimationEnd={()=>setWiggle(false)} aria-label="Ask Pip about Madhumita"><img src="/cheetah-cub-robot.png" alt=""/><span>Ask Pip!</span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="pet-dialog"><div className="pet-header"><img src="/cheetah-cub-robot.png" alt="Pip, a cheetah robot companion"/><div><DialogTitle>Hey, I’m Pip.</DialogTitle><DialogDescription>Madhumita’s tiny portfolio sidekick. Ask me about her work!</DialogDescription></div></div><div className="quick-questions">{faqs.slice(0,6).map(f=><button key={f.q} onClick={()=>ask(f.q)}>{f.q}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask(question)}}><label htmlFor="pet-question">Your question</label><div className="ask-row"><input id="pet-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500} required placeholder="What would you like to know?"/><button className="button primary">Ask</button></div></form>{asked&&<div aria-live="polite" className="pet-answer"><p className="asked">{asked}</p><p>{answer}</p></div>}{unknown&&<a href="#notes" onClick={()=>setOpen(false)}>Leave your contact details in a private note</a>}<p className="fine">Pip uses verified portfolio facts. Unanswered questions are saved privately and emailed to Madhumita.</p></DialogContent></Dialog></>
}
export default function Portfolio(){
 const [play,setPlay]=useState(false);
 return <><a className="skip" href="#main">Skip to content</a><header><a className="brand" href="#">madhu<span>mita.</span></a><nav aria-label="Main navigation"><a href="#projects">Work</a><a href="#experience">Experience</a><a href="#skills">Skills</a><a href="#notes">Leave a note</a></nav></header><main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">ROBOTICS · VISION · LEARNING</p><h1>Serious about<br/>robots.<br/><em>Curious about<br/>everything.</em></h1><p className="intro">I’m Madhumita, a robotics engineer working across computer vision, machine learning, and reinforcement learning.</p><p className="location">Boston, MA · Open to relocation anywhere</p><div className="actions"><a className="button primary" href="#projects">Explore my work</a><a className="button" href="/robotics-resume.pdf" target="_blank">Robotics résumé</a><a className="button" href="/ml-resume.pdf" target="_blank">ML résumé</a></div></div><div className={"hero-play "+(play?"playing":"")}><p className="sticker">A LITTLE WILD.<br/>A LOT OF CURIOSITY.</p><button className="hero-pet" onClick={()=>setPlay(!play)} aria-label={play?"Let Pip rest":"Make Pip bounce"}><img src="/cheetah-cub-robot.png" alt="Pip the tiny cheetah robot"/></button><p className="pet-caption">Tap Pip for a little happy dance.</p><div className="role-pills"><span>Robotics engineer</span><span>CV / ML engineer</span><span>RL engineer</span><span>Robotics scientist</span></div></div></section>
 <section id="projects"><Heading>Things I’ve built</Heading><p className="section-intro">From robot motion to learning systems. Pick a project and take a closer look.</p><Tabs defaultValue="All"><TabsList className="project-tabs" aria-label="Filter projects">{["All","Robotics","Learning","Systems"].map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList>{["All","Robotics","Learning","Systems"].map(c=><TabsContent value={c} key={c}><div className="project-grid">{projects.filter(p=>c==="All"||p.category===c).map(p=><Dialog key={p.title}><DialogTrigger asChild><button className={"project-card "+p.color}><div className="project-top"><span>{p.category}</span><span>{p.glyph}</span></div><h3>{p.title}</h3><p>{p.summary}</p><div className="tags">{p.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><span className="view-project">Explore project +</span></button></DialogTrigger><DialogContent className="project-dialog"><span className="tag">{p.category}</span><DialogTitle>{p.title}</DialogTitle><DialogDescription>{p.place} · {p.date}</DialogDescription><h4>The idea</h4><p>{p.summary}</p><h4>My contribution</h4><p>{p.detail}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><a href="https://github.com/Madhumita24" target="_blank" rel="noopener noreferrer">Browse my GitHub</a></DialogContent></Dialog>)}</div></TabsContent>)}</Tabs></section>
 <section id="experience"><Heading>Where I’ve contributed</Heading><div className="experience-grid"><article><p className="eyebrow">JANUARY–MARCH 2025 · BOSTON</p><h3>Northeastern University</h3><h4>Teaching Assistant · Reinforcement Learning</h4><ul><li>Evaluated student submissions and provided constructive feedback on reinforcement learning concepts.</li><li>Held office hours to clarify course material and assignment algorithms.</li><li>Guided problem-solving and debugging of RL implementations.</li></ul></article><article><p className="eyebrow">FEBRUARY–JUNE 2024 · HYDERABAD</p><h3>Sampradaya Vastra</h3><h4>Consultant · Machine Learning Engineering</h4><ul><li>Built and deployed a hybrid recommendation model combining SVD and k-NN.</li><li>Improved precision@k by 25% and recall by 20%.</li><li>Used scikit-learn, TensorFlow, grid search, content moderation, and stratified cross-validation.</li><li>Projected an 18% revenue increase for the website launch; this was a forecast.</li></ul></article></div></section>
 <section id="skills"><Heading>My toolkit</Heading><div className="skill-grid">{skills.map(s=><article key={s.title}><h3>{s.title}</h3><div className="tags">{s.items.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>
 <section id="education"><Heading>The learning never stops</Heading><div className="education-grid"><article><h3>Northeastern University</h3><h4>M.S. Robotics with Computer Science</h4><p>Robot Mechanics and Control · Reinforcement Learning · Human-Computer Interaction · Pattern Recognition and Computer Vision</p></article><article><h3>Malla Reddy Engineering College for Women</h3><h4>B.Tech. Computer Science and Engineering · June 2024</h4><p>Data Structures and Algorithms · Big Data Analytics · Operating Systems · Machine Learning · Database Management Systems · DevOps on AWS · Peer-to-Peer Protocols and Local Area Networks</p></article></div></section>
 <section id="notes"><Heading>A note, just between us</Heading><div className="notes-layout"><div><h3>Say hello.<br/>I’ll read it.</h3><p>Have feedback, an interesting problem, or a role that sounds like a fit? Leave me a private note.</p><p>These notes are never displayed publicly.</p></div><MessageForm kind="note"/></div></section>
 <section className="contact"><p className="eyebrow">LET’S BUILD SOMETHING THAT MOVES.</p><h2>Your next robotics<br/>or ML teammate?</h2><div className="contact-links"><a href="mailto:madhumitakol2402@gmail.com">madhumitakol2402@gmail.com</a><a href="tel:+16177783566">+1 617 778 3566</a></div><div className="actions"><a className="button" href="https://www.linkedin.com/in/madhumita-kolukuluri/" target="_blank" rel="noopener noreferrer">LinkedIn</a><a className="button" href="https://github.com/Madhumita24" target="_blank" rel="noopener noreferrer">GitHub</a></div></section></main><footer><span>© 2026 Madhumita Kolukuluri</span><a href="/inbox">Owner inbox</a><a href="#main">Back to top</a></footer><Pet/></>
}
