"use client";
import {useState} from "react";
import {Dialog,DialogContent,DialogDescription,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {faqs as originalFaqs} from "@/lib/portfolio";
import {initialContent,type Content} from "@/lib/content";
function Heading({children}:{children:React.ReactNode}){return <div className="heading-band"><h2>{children}</h2></div>}
export function MessageForm({kind,question,context,onSent}:{kind:"note"|"question";question?:string;context?:string;onSent?:(sent:boolean)=>void}){
 const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 return <form className="message-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setStatus("");const form=e.currentTarget;const data=new FormData(form);try{const r=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,name:data.get("name"),email:data.get("email"),body:question||(context?context+"\n\n":"")+String(data.get("body")||""),website:data.get("website")})});const result=await r.json() as {error?:string;emailSent:boolean};if(!r.ok)throw Error(result.error||"Please try again.");setStatus(kind==="note"?(result.emailSent?"Your note was saved privately and emailed to Madhumita.":"Your note was saved in Madhumita’s private inbox. Email delivery is temporarily unavailable."):result.emailSent?"Your question was saved and emailed to Madhumita.":"Your question was saved in Madhumita’s private inbox. Email delivery is not available yet.");form.reset();onSent?.(result.emailSent)}catch(err){setStatus(err instanceof Error?err.message:"Please try again.")}finally{setBusy(false)}}}>
 <div className="form-pair"><label>Your name <span>(optional)</span><input name="name" maxLength={80} autoComplete="name"/></label><label>Email <span>(optional, for a reply)</span><input name="email" type="email" maxLength={254} autoComplete="email"/></label></div>
 {!question&&<label>Your note<textarea name="body" required minLength={5} maxLength={2000} rows={4} placeholder="Tell me about the opportunity…"/></label>}
 <label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>
 <p className="fine">Only Madhumita can read submissions. Don’t include sensitive personal information.</p><button className="button primary" disabled={busy}>{busy?"Saving…":kind==="note"?"Leave a private note":"Send question to Madhumita"}</button><p role="status">{status}</p></form>
}
function Pet({content}:{content:Content}){
 const faqs=[{q:"What experience does she have?",patterns:[/experience/,/teaching/,/advisory/,/cultivarium/,/lab automation/,/smolvla/],answer:content.experiences.map(e=>`${e.role} at ${e.company} (${e.date}). ${e.points.join(" ")}`).join("\n\n")},{q:"What projects has she built?",patterns:[/project/,/wifi/,/localization/,/triangulat/,/dice/,/sorting/,/robotic arm/,/research assistant/,/summar/,/citation/,/multi.agent/,/stock/],answer:content.projects.map(p=>`${p.title}: ${p.summary} ${p.detail}`).join("\n\n")},{q:"What skills does she have?",patterns:[/skills?/,/languages?/,/tech(nical)? (stack|toolkit)/,/python/],answer:content.skills.map(s=>`${s.title}: ${s.items.join(", ")}`).join("\n")},...originalFaqs.filter(f=>["Is Madhumita open to relocation?","What roles is she looking for?","How can I contact Madhumita?","What did she study?"].includes(f.q))];
 const [open,setOpen]=useState(false);const [question,setQuestion]=useState("");const [asked,setAsked]=useState("");const [answer,setAnswer]=useState("");const [unknown,setUnknown]=useState(false);const [wiggle,setWiggle]=useState(false);
 async function ask(q:string){const clean=q.trim();if(!clean)return;setAsked(clean);setUnknown(false);const matched=faqs.find(f=>f.q.toLowerCase()===clean.toLowerCase())||(!/salary|visa|sponsor|citizen|available|start date|graduate|graduat|age|marri|relig|politic|address|gpa|years|favorite/i.test(clean)?faqs.find(f=>f.patterns.some(p=>p.test(clean.toLowerCase()))):undefined);if(matched){setAnswer(matched.answer)}else{setAnswer("I don’t have a verified answer to that. I’m forwarding your question to Madhumita…");setUnknown(true);try{const r=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"question",body:clean})});const result=await r.json() as {error?:string;emailSent:boolean};if(!r.ok)throw Error(result.error||"Please try again.");setAnswer(result.emailSent?"I don’t know that one! Your question was saved privately and emailed to Madhumita. Leave a private note with your email if you’d like a reply.":"I don’t know that one! Your question was saved in Madhumita’s private inbox. Email delivery is currently unavailable.")}catch(err){setAnswer("I don’t know that one, and couldn’t forward it. "+(err instanceof Error?err.message:"Please try again."))}}}
 return <><button className={"pet-launch "+(wiggle?"pet-wiggle":"")} onClick={()=>setOpen(true)} onMouseEnter={()=>setWiggle(true)} onAnimationEnd={()=>setWiggle(false)} aria-label="Ask Pip about Madhumita"><img src="/cheetah-cub-robot.png" alt=""/><span>Ask Pip!</span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="pet-dialog"><div className="pet-header"><img src="/cheetah-cub-robot.png" alt="Pip, a cheetah robot companion"/><div><DialogTitle>Hey, I’m Pip.</DialogTitle><DialogDescription>Madhumita’s tiny portfolio sidekick. Ask me about her work!</DialogDescription></div></div><div className="quick-questions">{faqs.slice(0,5).map(f=><button key={f.q} onClick={()=>ask(f.q)}>{f.q}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask(question)}}><label htmlFor="pet-question">Your question</label><div className="ask-row"><input id="pet-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500} required placeholder="What would you like to know?"/><button className="button primary">Ask</button></div></form>{asked&&<div aria-live="polite" className="pet-answer"><p className="asked">{asked}</p><p>{answer}</p></div>}{unknown&&<a href="#notes" onClick={()=>setOpen(false)}>Leave your contact details in a private note</a>}<p className="fine">Pip uses verified portfolio facts. Unanswered questions are saved privately and emailed to Madhumita.</p></DialogContent></Dialog></>
}
export default function Portfolio({content=initialContent}:{content?:Content}){
 const {projects,experiences,skills}=content;

 return <><a className="skip" href="#main">Skip to content</a><header><a className="brand" href="#">madhu<span>mita.</span></a><nav aria-label="Main navigation"><a href="#projects">Work</a><a href="#experience">Experience</a><a href="#skills">Skills</a><a href="/sidequests">Sidequests</a><a href="#notes">Leave a note</a></nav></header><main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">ROBOTICS · VISION · LEARNING</p><h1>Serious about<br/>robots.<br/><em>Curious about<br/>everything.</em></h1><p className="intro">I’m Madhumita, a robotics engineer working across computer vision, machine learning, and reinforcement learning.</p><p className="location">Boston, MA · Open to relocation anywhere</p><div className="actions"><a className="button primary" href="#projects">Explore my work</a></div></div><figure className="hero-portrait"><img src="/madhumita-portrait.png" alt="Madhumita smiling in a black suit against a red background" width={1132} height={1254} fetchPriority="high"/></figure></section>
 <section id="projects"><Heading>Things I’ve built</Heading><p className="section-intro">From robot motion to learning systems. Pick a project and take a closer look.</p><Tabs defaultValue="All"><TabsList className="project-tabs" aria-label="Filter projects">{["All","Robotics","Learning"].map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList>{["All","Robotics","Learning"].map(c=><TabsContent value={c} key={c}><div className="project-grid">{projects.filter(p=>c==="All"||p.category===c).map(p=><Dialog key={p.title}><DialogTrigger asChild><button className={"project-card "+p.color}><div className="project-top"><span>{p.category}</span><span>{p.glyph}</span></div><h3>{p.title}</h3><p>{p.summary}</p><div className="tags">{p.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><span className="view-project">Explore project +</span></button></DialogTrigger><DialogContent className="project-dialog"><span className="tag">{p.category}</span><DialogTitle>{p.title}</DialogTitle><DialogDescription>{[p.place,p.date].filter(Boolean).join(" · ")}</DialogDescription><h4>The idea</h4><p>{p.summary}</p><h4>My contribution</h4><p>{p.detail}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><a href="https://github.com/Madhumita24" target="_blank" rel="noopener noreferrer">Browse my GitHub</a></DialogContent></Dialog>)}</div></TabsContent>)}</Tabs></section>
 <section id="experience"><Heading>Experience & leadership</Heading><div className="experience-grid">{experiences.map(e=><article key={e.role}><p className="eyebrow">{e.date}</p><h3>{e.company}</h3><h4>{e.role}</h4><ul>{e.points.map(point=><li key={point}>{point}</li>)}</ul></article>)}</div></section> <section id="skills"><Heading>My toolkit</Heading><div className="skill-grid">{skills.map(s=><article key={s.title}><h3>{s.title}</h3><div className="tags">{s.items.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>
 <section id="education"><Heading>The learning never stops</Heading><div className="education-grid"><article><h3>Northeastern University</h3><h4>M.S. Robotics with Computer Science</h4><p>Robot Mechanics and Control · Reinforcement Learning · Human-Computer Interaction · Pattern Recognition and Computer Vision</p></article></div></section>
 <section id="notes"><Heading>Contact Madhumita</Heading><div className="notes-layout"><div><h3>Discuss an opportunity.</h3><p>Share a role, collaboration, or question. Your message goes directly to my private inbox.</p><p>These notes are never displayed publicly.</p></div><MessageForm kind="note"/></div></section>
 <section className="contact"><p className="eyebrow">LET’S BUILD SOMETHING THAT MOVES.</p><h2>Your next robotics<br/>or ML teammate?</h2><div className="contact-links"><a href="mailto:madhumitakol2402@gmail.com">madhumitakol2402@gmail.com</a><a href="tel:+16177783566">+1 617 778 3566</a></div><div className="actions"><a className="button" href="https://www.linkedin.com/in/madhumita-kolukuluri/" target="_blank" rel="noopener noreferrer">LinkedIn</a><a className="button" href="https://github.com/Madhumita24" target="_blank" rel="noopener noreferrer">GitHub</a></div></section></main><footer><a href="/manage">Manage portfolio</a><span>© 2026 Madhumita Kolukuluri</span><a href="/inbox">Owner inbox</a><a href="#main">Back to top</a></footer><Pet content={content}/></>
}
