export const projects=[
 {title:"Vision-guided dice sorting",category:"Robotics",color:"mint",date:"January–April 2025",place:"Northeastern University",summary:"A robotic arm that sees, classifies, and sorts dice by face value.",detail:"Developed a vision-guided system using ROS and convolutional neural networks to classify dice and coordinate precise robotic sorting through motion planning.",tags:["ROS","CNNs","Computer vision","Motion planning"],glyph:"01"},
 {title:"Multi-agent portfolio management",category:"Learning",color:"pink",date:"September–December 2024",place:"Northeastern University",summary:"Learning to make dynamic, risk-aware investment decisions.",detail:"Optimized stock portfolios with multi-agent reinforcement learning, integrating transaction costs and market volatility into dynamic decision-making and risk management.",tags:["Multi-agent RL","Risk management","Decision-making"],glyph:"02"},
 {title:"AI-powered research assistant",category:"Learning",color:"orange",date:"January–April 2025",place:"Northeastern University",summary:"Paper summaries, citations, and comparisons built around researchers.",detail:"Developed an AI-powered research assistant grounded in HCI principles and Shneiderman’s eight golden rules. Iterative user feedback guided paper summarization, citation retrieval, and intelligent comparison.",tags:["AI","HCI","User-centered design"],glyph:"03"},
 {title:"Cloud multimedia manager",category:"Systems",color:"blue",date:"January–April 2024",place:"Malla Reddy Engineering College for Women",summary:"A collaborative home for media with scalable, real-time access.",detail:"Designed a cloud-based multimedia management system for seamless storage, organization, and real-time access to media files, supporting scalability and collaboration.",tags:["Cloud computing","Media storage","Collaboration"],glyph:"04"}
];
export const skills=[
 {title:"Code",items:["Python","Java","SQL","C","HTML","Web development"]},
 {title:"Build & learn",items:["TensorFlow","scikit-learn","MATLAB","Simulink","ROS","CNNs","Reinforcement learning"]},
 {title:"Analyze & collaborate",items:["Power BI","MS Office","Teamwork","Leadership","Time management","Communication","Conflict management"]}
];
export const faqs=[
 {q:"Is Madhumita open to relocation?",patterns:[/relocat/,/where.*(live|based|located)/,/boston/,/location/],answer:"Madhumita is based in Boston, Massachusetts, and is open to relocating anywhere."},
 {q:"What roles is she looking for?",patterns:[/what.*roles?/,/job.*(interest|looking)/,/career/],answer:"She’s pursuing robotics engineer, computer vision / ML engineer, reinforcement learning engineer, and robotics scientist roles."},
 {q:"Tell me about the robotics project.",patterns:[/dice/,/robotic.*project/,/sorting/,/robotic arm/],answer:"Her vision-guided dice sorting project uses ROS and CNNs to classify dice by face value and coordinate robotic sorting with motion planning. It was developed at Northeastern University in January–April 2025."},
 {q:"What is her reinforcement learning project?",patterns:[/reinforcement.*project/,/portfolio management/,/multi.agent/,/stock/],answer:"She optimized stock portfolios with multi-agent reinforcement learning, accounting for transaction costs and market volatility to support dynamic, risk-aware decisions."},
 {q:"What skills does she have?",patterns:[/skills?/,/languages?/,/tech(nical)? (stack|toolkit)/,/python/],answer:"Her résumé lists Python, Java, SQL, C, HTML, web development, TensorFlow, scikit-learn, MATLAB, Simulink, Power BI, and MS Office. Her projects also use ROS, CNNs, and reinforcement learning."},
 {q:"How can I contact Madhumita?",patterns:[/contact/,/phone/,/email/,/linkedin/],answer:"Email madhumitakol2402@gmail.com or call +1 617 778 3566. Her LinkedIn is linkedin.com/in/madhumita-kolukuluri/."},
 {q:"Tell me about her research assistant.",patterns:[/research assistant/,/summar/,/citation/],answer:"Her AI research assistant supports paper summarization, citation retrieval, and intelligent comparison, using HCI principles and iterative feedback from academic researchers."},
 {q:"What did she study?",patterns:[/education/,/degree/,/stud(y|ied)/,/university/],answer:"Her résumé lists an M.S. in Robotics with Computer Science at Northeastern University and a B.Tech. in Computer Science and Engineering at Malla Reddy Engineering College for Women."}
];
